### ISSUE TITLE
Error, not able to implement @partial_credit decorator

### ISSUE THREAD

**Issue by Manojbhat09** [gradescope/gradescope-utils#11]
I am getting this error when I use partial_credit decorator 

 @partial_credit(10)\nNameError: name 'partial_credit' is not defined\n\n"

I use it like this:
@partial_credit(10)
    def test_exercise_1(self, set_score=None):
        """Exercise 1 answers"""
        flag = 0
        ...
        if(flag == 0):
            set_score((8-flag)*/8)
            return 1            

Where am I going wrong?

**Comment by ibrahima** [comment]
Did you make sure to import the decorator before using it? Otherwise it won't be defined.

E.g. see https://github.com/gradescope/autograder_samples/blob/master/python/src/tests/test_simple.py#L2

**Comment by Manojbhat09** [comment]
Hello @ibrahima ,
Thank you very much for your instant reply on the issue. 
We have fixed the AutoGrader code with the new additions. 

We are still figuring out how to limit the number of submissions by the student by max 2 submissions per 24 hours. Is it possible to implement through autograder this git package? 

Please inform us.

**Comment by ibrahima** [comment]
No, this package won't help with that, but you can refer to [our documentation site](https://gradescope-autograders.readthedocs.io/en/latest/submission_metadata/) to see the information you'd need to do that. Please follow up by emailing help@gradescope.com if you have further questions about that. Thanks!
