### ISSUE TITLE
Error no such file or directory

### ISSUE THREAD

**Issue by roroar** [gradescope/gradescope-utils#12]
Hi, I tried to run python setup.sh and I got this :
Could not open requirements file: [Errno 2] No such file or directory: '/autograder/source/requirements.txt'

any ideas?

**Comment by ibrahima** [comment]
If you are using `setup.sh` from the sample Python autograder code, you would need a requirements.txt file to install your Python dependencies. However, this does not seem to have anything to do with this package - can you email us at help@gradescope.com with further details and we can try to help you there? Thanks!
