### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by nihilistkitten** [gradescope/gradescope-utils#24]
It would be awesome if y'all would be willing to put a license on this code. Preferably MIT or Apache, but any clarity would be helpful.

**Comment by stevenbell** [comment]
I second this... this is good stuff and I'd like to build on it, but can't do that in good conscience without a known license.  Perhaps @ibrahima or @mDibyo could comment?  Thanks!

**Comment by ibrahima** [comment]
Thanks for asking, let me consult with some others and get back to you all!
