### ISSUE TITLE
Setting a default visibility

### ISSUE THREAD

**Issue by omoindrot** [gradescope/gradescope-utils#3]
Would there be a way to set a default visibility other than `visible` for all tests?

Right now I didn't find any, and adding all the `@visibility("after_published")` decorators is quite annoying.

Thank you very much !

**Comment by ibrahima** [comment]
Hi Olivier! Sorry I didn't see this earlier, but as of a couple weeks ago, this is now possible. You just need to pass it in as an argument to JSONTestRunner. See https://github.com/gradescope/gradescope-utils/commit/a4f636273b2772d4314ad7533f3869550ccca367#diff-9d0ff16ed9674c38f6820465bfc05a4a for the commit that introduces the feature, and you can see an example of using it here: https://github.com/gradescope/autograder_samples/commit/c978a8c9b8952c81fab10b6cebb80d0ff69eeaa8
